name = "dlp-api"
main = "src/index.ts"
compatibility_date = "2026-03-20"

[vars]
APP_SECRET = "CHANGE_ME_TO_A_LONG_RANDOM_SECRET"

[[d1_databases]]
binding = "DB"
database_name = "dlp_db"
database_id = "2dc13104-d286-41c0-83d5-3970094e76a7"

[[r2_buckets]]
binding = "R2"
bucket_name = "dlp-uploads"


[[durable_objects.bindings]]
name = "RATE_LIMITER"
class_name = "RateLimiter"

[[migrations]]
tag = "v1"
new_classes = ["RateLimiter"]


[triggers]
crons = ["0 * * * *"]
