import * as XLSX from 'xlsx';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const WORKBOOK_PATH = resolve(process.cwd(), 'src/assets/mcheyne_plan.xlsx');
const OUTPUT_SQL_PATH = resolve(process.cwd(), 'migrations/0002_seed_mcheyne_plan.sql');
const SKIP_SHEETS = new Set(['Sheet2', 'Sheet3']);

const DAYS_IN_MONTH = {
  1: 31,
  2: 28,
  3: 31,
  4: 30,
  5: 31,
  6: 30,
  7: 31,
  8: 31,
  9: 30,
  10: 31,
  11: 30,
  12: 31
};

function escSql(value) {
  return String(value ?? '').replace(/'/g, "''").trim();
}

function normalizeText(value) {
  return String(value ?? '').replace(/\s+/g, ' ').trim();
}

function parseMonth(value) {
  const text = normalizeText(value);
  const match = text.match(/^(\d{1,2})월$/);
  return match ? Number(match[1]) : null;
}

function parseDay(value) {
  const text = normalizeText(value);
  const match = text.match(/^(\d{1,2})일$/);
  return match ? Number(match[1]) : null;
}

function getCellText(sheet, rowIndexZeroBased, colIndexZeroBased) {
  const address = XLSX.utils.encode_cell({ r: rowIndexZeroBased, c: colIndexZeroBased });
  return normalizeText(sheet[address]?.v);
}

function readBlock(sheet, range, { monthCol, dayCol, readingCols, sheetName, blockName }) {
  const rows = [];
  let currentMonth = null;

  for (let r = range.s.r; r <= range.e.r; r += 1) {
    const monthText = getCellText(sheet, r, monthCol);
    const month = parseMonth(monthText);
    if (month) currentMonth = month;

    const dayText = getCellText(sheet, r, dayCol);
    const day = parseDay(dayText);
    if (!currentMonth || !day) continue;

    const readings = readingCols.map((col) => getCellText(sheet, r, col));
    if (readings.some((item) => !item)) {
      throw new Error(
        `Missing reading detected: sheet=${sheetName}, block=${blockName}, month=${currentMonth}, day=${day}, readings=${JSON.stringify(readings)}`
      );
    }

    rows.push({ month: currentMonth, day, readings, sheetName, blockName });
  }

  return rows;
}

function parseWorkbook(filePath) {
  const workbook = XLSX.read(readFileSync(filePath), { type: 'buffer' });
  const rows = [];

  for (const sheetName of workbook.SheetNames) {
    if (SKIP_SHEETS.has(sheetName)) continue;

    const sheet = workbook.Sheets[sheetName];
    const ref = sheet['!ref'];
    if (!ref) continue;
    const range = XLSX.utils.decode_range(ref);

    rows.push(
      ...readBlock(sheet, range, {
        monthCol: 1,
        dayCol: 1,
        readingCols: [2, 3, 4, 5],
        sheetName,
        blockName: 'LEFT'
      })
    );

    rows.push(
      ...readBlock(sheet, range, {
        monthCol: 7,
        dayCol: 7,
        readingCols: [8, 9, 10, 11],
        sheetName,
        blockName: 'RIGHT'
      })
    );
  }

  return rows;
}

function validateRows(rows) {
  if (rows.length !== 365) {
    throw new Error(`Expected 365 plan rows, but got ${rows.length}`);
  }

  const seen = new Set();
  for (const row of rows) {
    if (!Number.isInteger(row.month) || row.month < 1 || row.month > 12) {
      throw new Error(`Invalid month: ${JSON.stringify(row)}`);
    }

    const maxDay = DAYS_IN_MONTH[row.month];
    if (!Number.isInteger(row.day) || row.day < 1 || row.day > maxDay) {
      throw new Error(`Invalid day range: ${JSON.stringify(row)}`);
    }

    if (!Array.isArray(row.readings) || row.readings.length !== 4 || row.readings.some((item) => !item)) {
      throw new Error(`Invalid readings: ${JSON.stringify(row)}`);
    }

    const key = `${row.month}-${row.day}`;
    if (seen.has(key)) {
      throw new Error(`Duplicate month/day detected: ${key}`);
    }
    seen.add(key);
  }

  for (const [monthText, expectedCount] of Object.entries(DAYS_IN_MONTH)) {
    const month = Number(monthText);
    const actualCount = rows.filter((row) => row.month === month).length;
    if (actualCount !== expectedCount) {
      throw new Error(`Month ${month} should have ${expectedCount} rows, but got ${actualCount}`);
    }
  }
}

function toSeedSql(rows) {
  const lines = [
    '-- Auto-generated by src/scripts/generate_mcheyne_seed.mjs',
    '-- Cloudflare D1 friendly: no explicit BEGIN/COMMIT/SAVEPOINT statements',
    'DELETE FROM mcheyne_plan;'
  ];

  for (const row of rows) {
    const [reading1, reading2, reading3, reading4] = row.readings;
    lines.push(
      `INSERT INTO mcheyne_plan (month, day, reading1, reading2, reading3, reading4) VALUES (${row.month}, ${row.day}, '${escSql(reading1)}', '${escSql(reading2)}', '${escSql(reading3)}', '${escSql(reading4)}');`
    );
  }

  lines.push('');
  return lines.join('\n');
}

function main() {
  const rows = parseWorkbook(WORKBOOK_PATH).sort((a, b) => a.month - b.month || a.day - b.day);
  validateRows(rows);

  writeFileSync(OUTPUT_SQL_PATH, toSeedSql(rows), 'utf-8');

  const first = rows[0];
  const last = rows[rows.length - 1];
  console.log(`[OK] 0002_seed_mcheyne_plan.sql generated. rows=${rows.length}`);
  console.log(`[OK] first=${first.month}-${first.day} / last=${last.month}-${last.day}`);
}

main();
