import * as XLSX from 'xlsx';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

function escSql(s) {
  return String(s ?? '').replace(/'/g, "''").trim();
}

function isMonthCell(v) {
  return typeof v === 'string' && /^\d{1,2}월$/.test(v.trim());
}

function isDayCell(v) {
  return typeof v === 'string' && /^\d{1,2}일$/.test(v.trim());
}

function isReadingCell(v) {
  if (typeof v !== 'string') return false;
  const t = v.trim();
  if (!t) return false;
  if (isMonthCell(t) || isDayCell(t)) return false;
  return /장|편|서|기|복음|행전|계시록|상|하|전|후|~|:/.test(t);
}

function parseWorkbook(filePath) {
  const buf = readFileSync(filePath);
  const wb = XLSX.read(buf, { type: 'buffer' });

  const rows = [];

  for (const sheetName of wb.SheetNames) {
    if (sheetName === 'Sheet2' || sheetName === 'Sheet3') continue;

    const ws = wb.Sheets[sheetName];
    const grid = XLSX.utils.sheet_to_json(ws, { header: 1, raw: false });

    let currentMonth = null;

    for (const r of grid) {
      for (const cell of r) {
        if (isMonthCell(cell)) {
          currentMonth = Number(cell.trim().replace('월', ''));
          break;
        }
      }

      const dayCell = r.find(isDayCell);
      if (!dayCell || !currentMonth) continue;

      const day = Number(dayCell.trim().replace('일', ''));
      const readings = r.filter(isReadingCell).map((x) => x.trim());

      const uniq = [];
      for (const t of readings) {
        const cleaned = t.replace(/\s+/g, ' ').trim();
        if (!cleaned) continue;
        if (!uniq.includes(cleaned)) uniq.push(cleaned);
      }

      if (uniq.length >= 4) rows.push({ month: currentMonth, day, readings: uniq.slice(0, 4) });
    }
  }

  return rows;
}

function toSeedSql(rows) {
  const lines = [];
  lines.push('-- Auto-generated by src/scripts/generate_mcheyne_seed.mjs');
  lines.push('BEGIN;');
  lines.push('DELETE FROM mcheyne_plan;');

  for (const r of rows) {
    const [a, b, c, d] = r.readings;
    lines.push(
      `INSERT INTO mcheyne_plan (month, day, reading1, reading2, reading3, reading4) VALUES (${r.month}, ${r.day}, '${escSql(a)}', '${escSql(b)}', '${escSql(c)}', '${escSql(d)}');`
    );
  }

  lines.push('COMMIT;');
  lines.push('');
  return lines.join('\n');
}

const xlsxPath = resolve(process.cwd(), 'src/assets/mcheyne_plan.xlsx');
const outPath = resolve(process.cwd(), 'migrations/0002_seed_mcheyne_plan.sql');

const rows = parseWorkbook(xlsxPath);
writeFileSync(outPath, toSeedSql(rows), 'utf-8');

console.log(`[OK] 0002_seed_mcheyne_plan.sql generated. rows=${rows.length}`);
